version: '2'
services:

  postgres:
    image: postgres:9.4.6
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=""
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data

  web:
    build: docker/web
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    links:
      - postgres


  util:
    build: docker/util
    ports:
      - "8001:80"
    links:
      - postgres


